# Generated by Django 3.2.5 on 2021-08-16 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_alter_servico_service_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='servico',
            name='service_category',
            field=models.CharField(default=1, max_length=40),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='servico',
            name='slug',
            field=models.SlugField(max_length=40, unique=True),
        ),
    ]
